### ISSUE TITLE
[BUG] Error Installing on Windows 11- Couldn't load plugin 'QGIS_FMV' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by xchido** [All4Gis/QGISFMV#124]
Tried installing the plugin using the plugin manager from zip and selecting it from the list but it keeps failing to install. 

It goes as far as asking if I wan to install the FFMPEG dependencies and when I continue it gives me the error message below.

```
Couldn't load plugin 'QGIS_FMV' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'cv2' 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\__init__.py", line 49, in classFactory
    from .QgsFmv import Fmv
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    # Work around bug https://github.com/google/earthengine-api/issues/181
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\QgsFmv.py", line 35, in 
    from QGIS_FMV.manager.QgsManager import FmvManager
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    # Work around bug https://github.com/google/earthengine-api/issues/181
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsManager.py", line 20, in 
    from QGIS_FMV.player.QgsFmvDrawToolBar import DrawToolBar as draw
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    # Work around bug https://github.com/google/earthengine-api/issues/181
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\player\QgsFmvDrawToolBar.py", line 15, in 
    from QGIS_FMV.utils.QgsFmvUtils import (GetSensor,
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    # Work around bug https://github.com/google/earthengine-api/issues/181
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\utils\QgsFmvUtils.py", line 61, in 
    from cv2 import (COLOR_BGR2RGB,
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 38, in __wrapping_ee_import__
    _module_ = __builtin_import__(name, *args, **kwargs)
  File "C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ee_plugin\__init__.py", line 32, in __wrapping_ee_import__
    # Work around bug https://github.com/google/earthengine-api/issues/181
  File "C:\PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'cv2'


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.22.8-Białowieża Białowieża, 8d5e9761df 

Python Path:
C:/PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python
C:/Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS32~1.8/apps/qgis-ltr/./python/plugins
C:\Program Files\QGIS 3.22.8\bin\python39.zip
C:\PROGRA~1\QGIS32~1.8\apps\Python39\DLLs
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib
C:\Program Files\QGIS 3.22.8\bin
C:\PROGRA~1\QGIS32~1.8\apps\Python39
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS32~1.8\apps\Python39\lib\site-packages\Pythonwin
C:/Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\ee_plugin\extlibs_windows
C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis2web
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qgis_resource_sharing\ext_libs
X:/NewLib/Sikand Projects Map
C:\Users/jorge/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qgis_resource_sharing
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS_FMV
D:/eclipse/plugins/org.python.pydev.core_7.5.0.202001101138/pysrc
C:\Users\jorge\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\QGIS_FMV
D:/eclipse/plugins/org.python.pydev.core_7.5.0.202001101138/pysrc
```

**This is what I am using:**
- Windows 11 fully patched
- _QGIS version 3.22.8-Białowieża
- QGIS code revision 8d5e9761df
- Qt version 5.15.3
- Python version 3.9.5
- GDAL/OGR version 3.5.0
- PROJ version 9.0.1
- EPSG Registry database version v10.064 (2022-05-19)
- GEOS version 3.10.3-CAPI-1.16.1
- SQLite version 3.38.1
- PDAL version 2.3.0
- PostgreSQL client version 14.3
- SpatiaLite version 5.0.1
- QWT version 6.1.6
- QScintilla2 version 2.13.1
- OS version Windows 10 Version 2009
- 
- Active Python plugins
- AutomaticBackup-master 1.0
- DataPlotly 3.9.2
- ee_plugin 0.0.5
- ImportPhotos 3.0.4
- qgis2web 3.16.0
- qgis_gee_data_catalog 0.4.3
- qgis_resource_sharing 1.0.0
- temporalprofiletool 2.0.3
- db_manager 0.1.20
- grassprovider 2.12.99
- MetaSearch 0.3.5
- processing 2.12.99
- sagaprovider 2.12.99_

**Desktop:**
 - OS: [Windows 11]
 - QGIS Version [3.11.8]
 - Plugin Version [QGIS Full Motion Video 1.15]

**Comment by All4Gis** [comment]
you need to install opencv, this is the error, check this answers https://gis.stackexchange.com/questions/355217/using-opencv-function-in-pyqgis-module-not-found
