### ISSUE TITLE
[BUG]: IndexError: list index out of range

### ISSUE THREAD

**Issue by kcramos19** [All4Gis/QGISFMV#76]
IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/../QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsMultiplexor.py", line 218, in CreateCSV
    self.ReadCSVRecordings(input_metadata)
  File "C:/../QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsMultiplexor.py", line 593, in ReadCSVRecordings
    self.CreateDJICsv(rows_list, csv_raw)
  File "C:/../QGIS/QGIS3\profiles\default/python/plugins\QGIS_FMV\manager\QgsMultiplexor.py", line 617, in CreateDJICsv
    csv.writer(f_output).writerows(itertools.islice(csv_input, int(values[0]), int(values[-1])))

This appears after clicking the Extract Recording.
Thank you in advance

**Comment by All4Gis** [comment]
thanks for your feedback, i will try to reproduce it

**Comment by All4Gis** [comment]
Can you share your video and dji csv?

**Comment by All4Gis** [comment]
We close for lack of feedback
